api = "0.10"

[buildpack]
id = "joshwlewis/erlang-engine"
version = "0.1.0"
name = "Installs the erlang runtime"

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "arm64"

[[targets]]
os = "linux"
arch = "amd64"
